// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAghmDavdcabxXJaGrdyU2uFhNW49urFqg',
    appId: '1:240925805327:web:da3b86f3fc3574c2434c7a',
    messagingSenderId: '240925805327',
    projectId: 'table-next-pro',
    authDomain: 'table-next-pro.firebaseapp.com',
    storageBucket: 'table-next-pro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-aKgQKODxQQvqo0DZjDz2My6P0x9lbfM',
    appId: '1:240925805327:android:adf3ed840ed97dd8434c7a',
    messagingSenderId: '240925805327',
    projectId: 'table-next-pro',
    storageBucket: 'table-next-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6q4SR_S4ToAQk9q_hWWGB5CBD68CyI0U',
    appId: '1:240925805327:ios:27447cb953af5bfa434c7a',
    messagingSenderId: '240925805327',
    projectId: 'table-next-pro',
    storageBucket: 'table-next-pro.firebasestorage.app',
    iosBundleId: 'com.omarfahim.tableNextPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6q4SR_S4ToAQk9q_hWWGB5CBD68CyI0U',
    appId: '1:240925805327:ios:27447cb953af5bfa434c7a',
    messagingSenderId: '240925805327',
    projectId: 'table-next-pro',
    storageBucket: 'table-next-pro.firebasestorage.app',
    iosBundleId: 'com.omarfahim.tableNextPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAghmDavdcabxXJaGrdyU2uFhNW49urFqg',
    appId: '1:240925805327:web:bd82ffeadb34c23b434c7a',
    messagingSenderId: '240925805327',
    projectId: 'table-next-pro',
    authDomain: 'table-next-pro.firebaseapp.com',
    storageBucket: 'table-next-pro.firebasestorage.app',
  );
}
